import simbench as sb
import pandas as pd
import numpy as np
import warnings
import sys
import inspect

# 尝试导入 VeraGrid
try:
    import GC_PandaPowerImporter
    from VeraGridEngine import api as gce
except ImportError:
    print("❌ 缺少 VeraGrid 依赖")
    exit()

warnings.filterwarnings('ignore')

# 输出文件
OUTPUT_FILE = "veragrid_api_reference.txt"


class Logger(object):
    def __init__(self):
        self.terminal = sys.stdout
        self.log = open(OUTPUT_FILE, "w", encoding='utf-8')

    def write(self, message):
        self.terminal.write(message)
        self.log.write(message)

    def flush(self):
        pass


def inspect_obj(obj_name, obj, show_values=True):
    print(f"\n{'=' * 60}")
    print(f"📦 OBJECT CLASS: {obj_name}")
    print(f"   Type: {type(obj)}")
    print(f"{'=' * 60}")

    # 获取所有非魔法属性
    attrs = [a for a in dir(obj) if not a.startswith('__')]
    attrs.sort()

    print(f"{'Attribute Name':<35} | {'Type':<20} | {'Current Value (Example)'}")
    print("-" * 90)

    for attr in attrs:
        try:
            val = getattr(obj, attr)
            val_type = type(val).__name__

            # 跳过方法(Method)，只看属性(Property/Data)
            if inspect.ismethod(val) or inspect.isfunction(val):
                continue

            val_str = str(val)
            if len(val_str) > 50: val_str = val_str[:47] + "..."

            # 特殊处理 Enum，防止报错
            if "Enum" in val_type or "int" in val_type:
                try:
                    if hasattr(val, 'value'): val_str = f"Enum({val.value})"
                except:
                    pass

            print(f".{attr:<34} | {val_type:<20} | {val_str}")
        except Exception as e:
            print(f".{attr:<34} | {'Error':<20} | {e}")


def main():
    # 重定向输出到文件
    sys.stdout = Logger()

    print(f"🚀 开始生成 VeraGrid API 参考手册...")
    print(f"📅 Generated by script. Target: VeraGrid/GridCal internal structure inspection.\n")

    # 1. 加载模型
    sb_code = "1-MV-urban--0-sw"
    net_pp = sb.get_simbench_net(sb_code)
    grid = GC_PandaPowerImporter.PP2GC(net_pp)

    print(f"✅ 模型加载成功: {sb_code}")

    # ==========================================
    # 1. 核心组件解剖
    # ==========================================
    print("\n\n" + "#" * 60)
    print("PART 1: 核心电网组件 (Components)")
    print("#" * 60)

    # Bus
    if len(grid.buses) > 0:
        inspect_obj("Bus (节点)", grid.buses[0])

    # Generator (重点！)
    # 找一个 sgen，再找一个 ext_grid
    sgen = next((g for g in grid.generators if "sgen" in getattr(g, 'name', '')), None)
    ext_grid = next((g for g in grid.generators if "Ext_Grid" in getattr(g, 'name', '')), None)

    if sgen: inspect_obj("Generator (分布式光伏)", sgen)
    if ext_grid: inspect_obj("Generator (平衡节点/外网)", ext_grid)

    # Load
    if len(grid.loads) > 0:
        inspect_obj("Load (负荷)", grid.loads[0])

    # Line
    lines = getattr(grid, 'lines', [])
    if len(lines) > 0:
        inspect_obj("Line (线路)", lines[0])

    # Transformer
    trafos = getattr(grid, 'transformers', [])
    if len(trafos) > 0:
        inspect_obj("Transformer (变压器)", trafos[0])

    # ==========================================
    # 2. 求解器配置解剖
    # ==========================================
    print("\n\n" + "#" * 60)
    print("PART 2: 求解器配置 (Solver Options)")
    print("#" * 60)

    try:
        # 尝试创建一个 AC 求解器选项
        opts = gce.PowerFlowOptions(gce.SolverType.NR)
        inspect_obj("PowerFlowOptions (Newton-Raphson)", opts)
    except:
        print("❌ 无法创建默认 PowerFlowOptions")

    # ==========================================
    # 3. 结果对象解剖
    # ==========================================
    print("\n\n" + "#" * 60)
    print("PART 3: 计算结果 (Results)")
    print("#" * 60)

    try:
        # 跑一次简单的 PF
        driver = gce.PowerFlowDriver(grid, opts)
        driver.run()

        if driver.results:
            inspect_obj("PowerFlowResults", driver.results)

            # 顺便打印一下关键数组的形状，方便理解
            print("\n[关键数据维度检查]:")
            res = driver.results
            if hasattr(res, 'voltage'): print(f"  voltage.shape: {np.shape(res.voltage)}")
            if hasattr(res, 'Sbus'): print(f"  Sbus.shape:    {np.shape(res.Sbus)}")
            if hasattr(res, 'loading'): print(f"  loading.shape: {np.shape(res.loading)}")

    except Exception as e:
        print(f"❌ 运行 PF 失败: {e}")

    print("\n\n✅ 完成！请查看当前目录下的 veragrid_api_reference.txt")


if __name__ == "__main__":
    main()